apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: infrastructure
  labels:
    app: mongo
    tier: database
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "mongo123"
  MONGO_CONNECTION_STRING: "mongodb://admin:mongo123@mongo-srv.infrastructure.svc.cluster.local:27017/microservices_mongo?authSource=admin"
