# ============================================
# MongoDB - Secrets
# ============================================

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: infrastructure
  labels:
    app: mongodb
    tier: database
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "mongodb123"
