apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app: grafana
    tier: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-srv.monitoring.svc.cluster.local:9090",
                "version": 1
            },
            {
                "access": "proxy",
                "editable": true,
                "name": "Elasticsearch",
                "orgId": 1,
                "type": "elasticsearch",
                "url": "http://elasticsearch-lb.monitoring.svc.cluster.local:9200",
                "database": "microservices-logs-*",
                "jsonData": {
                    "esVersion": "8.0.0",
                    "timeField": "@timestamp",
                    "interval": "Daily",
                    "logMessageField": "log",
                    "logLevelField": "level"
                },
                "version": 1
            }
        ]
    }
