# ============================================
# Leave Service - ServiceAccount
# ============================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: leave-sa
  namespace: graduate-project
  labels:
    app: leave
    tier: application
automountServiceAccountToken: true
