apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-daemonset
  namespace: monitoring
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      tolerations:
        - operator: Exists # Chạy trên tất cả các node kể cả Master
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.16-debian-elasticsearch8-1
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch-srv.monitoring.svc.cluster.local"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Tối ưu Ruby GC cho RAM thấp
            - name: RUBY_GC_HEAP_GROWTH_FACTOR
              value: "1.1"
            - name: RUBY_GC_MALLOC_LIMIT
              value: "8000000"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 150Mi # Tăng nhẹ để gánh Buffer 64MB + Plugin
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentd-config-volume
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
            - name: fluentd-buffer
              mountPath: /tmp/fluentd-buffers
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentd-config-volume
          configMap:
            name: fluentd-config
        - name: fluentd-buffer
          emptyDir:
            sizeLimit: 500Mi # Giới hạn đĩa ảo để không gây DiskPressure