apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: infrastructure
  labels:
    app: rabbitmq
    tier: messaging
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "rabbitmq123"
  RABBITMQ_CONNECTION_STRING: "amqp://admin:rabbitmq123@rabbitmq-srv.infrastructure.svc.cluster.local:5672/"
