# ============================================
# Employee Service - ServiceAccount
# ============================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: employee-sa
  namespace: default
  labels:
    app: employee
    tier: application
automountServiceAccountToken: true
