apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: infrastructure
  labels:
    app: postgres
    tier: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres123"
  DATABASE_URL: "postgresql://postgres:postgres123@postgres-srv.infrastructure.svc.cluster.local:5432/microservices_db"
