# ============================================
# Attendance Service - ServiceAccount
# ============================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: attendance-sa
  namespace: graduate-project
  labels:
    app: attendance
    tier: application
automountServiceAccountToken: true
